/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2_ayleenescobaryjazminsalgado;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author famil
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_ProductID = new javax.swing.JTextField();
        TF_OrderID = new javax.swing.JTextField();
        TF_ShipMode = new javax.swing.JTextField();
        TF_Segment = new javax.swing.JTextField();
        TF_State = new javax.swing.JTextField();
        TF_Sales = new javax.swing.JTextField();
        TF_ProductName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TF_OrderDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF_ShipDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF_CustomerID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TF_CustomerName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TF_Country = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TF_City = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TF_Postal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TF_Region = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TF_Category = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TF_Sub_Category = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TF_Quantity = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TF_Discount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TF_Profit = new javax.swing.JTextField();
        Bttn_AgregarRegistro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Bttn_Orders = new javax.swing.JButton();
        Bttn_Details = new javax.swing.JButton();
        Bttn_Customers = new javax.swing.JButton();
        Bttn_Products = new javax.swing.JButton();
        Bttn_Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Registro = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Bttn_UpdateTabla = new javax.swing.JButton();
        Bttn_Eliminar = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Order ID:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ship Mode:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Segment:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("State:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Product ID:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Product Name:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sales:");

        TF_ProductID.setText("texto");

        TF_OrderID.setText("texto");

        TF_ShipMode.setText("texto");

        TF_Segment.setText("texto");

        TF_State.setText("texto");

        TF_Sales.setText("11");

        TF_ProductName.setText("texto");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Order Date:");

        TF_OrderDate.setText("11/03/2004\n");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ship Date:");

        TF_ShipDate.setText("11/03/2004\n");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Customer ID:");

        TF_CustomerID.setText("texto");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Customer Name:");

        TF_CustomerName.setText("texto");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Country:");

        TF_Country.setText("texto");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("City:");

        TF_City.setText("texto");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Postal Code:");

        TF_Postal.setText("11");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Region:");

        TF_Region.setText("texto");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Category:");

        TF_Category.setText("texto");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Sub-Category:");

        TF_Sub_Category.setText("texto");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Quantity:");

        TF_Quantity.setText("11");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Discount:");

        TF_Discount.setText("11");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Profit:");

        TF_Profit.setText("11");

        Bttn_AgregarRegistro.setText("Agregar Registro");
        Bttn_AgregarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bttn_AgregarRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TF_State, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TF_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TF_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TF_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel15)
                                        .addGap(171, 171, 171))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TF_ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_Region, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Bttn_AgregarRegistro)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(TF_Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TF_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(TF_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(TF_Profit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(TF_ProductName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_ShipMode, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Segment, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_OrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_CustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(TF_ShipDate)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addComponent(jLabel13)
                                .addGap(33, 33, 33)
                                .addComponent(TF_City)))))
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TF_OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(TF_ShipDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TF_ShipMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TF_Segment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(TF_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TF_OrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(TF_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TF_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(TF_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TF_ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(TF_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(TF_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TF_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TF_Sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(TF_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(TF_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(TF_Profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Bttn_AgregarRegistro))
                    .addComponent(jLabel15))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Registro", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Bttn_Orders.setBackground(new java.awt.Color(0, 153, 51));
        Bttn_Orders.setText("Orders");
        Bttn_Orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bttn_OrdersMouseClicked(evt);
            }
        });

        Bttn_Details.setBackground(new java.awt.Color(255, 102, 0));
        Bttn_Details.setText("Details");
        Bttn_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bttn_DetailsMouseClicked(evt);
            }
        });

        Bttn_Customers.setBackground(new java.awt.Color(204, 0, 51));
        Bttn_Customers.setText("Customers");
        Bttn_Customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bttn_CustomersMouseClicked(evt);
            }
        });

        Bttn_Products.setBackground(new java.awt.Color(0, 102, 204));
        Bttn_Products.setText("Products");
        Bttn_Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bttn_ProductsMouseClicked(evt);
            }
        });

        Bttn_Clear.setBackground(new java.awt.Color(255, 255, 255));
        Bttn_Clear.setText("Clear");
        Bttn_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bttn_ClearMouseClicked(evt);
            }
        });

        jList_Registro.setModel(new DefaultListModel<>()
        );
        jScrollPane1.setViewportView(jList_Registro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Bttn_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bttn_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bttn_Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bttn_Products, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(Bttn_Clear)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bttn_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bttn_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bttn_Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bttn_Products, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bttn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Registro", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Row ID", "Order ID", "Order Date", "Customer ID", "Country", "City", "Product ID", "Sales"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        Bttn_UpdateTabla.setText("Update Tabla");
        Bttn_UpdateTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bttn_UpdateTablaMouseClicked(evt);
            }
        });
        Bttn_UpdateTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn_UpdateTablaActionPerformed(evt);
            }
        });

        Bttn_Eliminar.setText("Eliminar Registro");
        Bttn_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bttn_EliminarMouseClicked(evt);
            }
        });
        Bttn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn_EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Bttn_UpdateTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bttn_Eliminar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Bttn_UpdateTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Bttn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        jTabbedPane1.addTab("Eliminar Registro", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bttn_UpdateTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn_UpdateTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bttn_UpdateTablaActionPerformed

    private void Bttn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bttn_EliminarActionPerformed

    private void Bttn_AgregarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bttn_AgregarRegistroMouseClicked
        ab = new AdministrarBarra(jProgressBar1, 6, Color.yellow);
        ab.start();

        db.conectar();
        try {
            String orderid = TF_OrderID.getText(),
                    orderdate = TF_OrderDate.getText(),
                    shipdate = TF_ShipDate.getText(),
                    shipmode = TF_ShipMode.getText(),
                    customerid = TF_CustomerID.getText(),
                    customername = TF_CustomerName.getText(),
                    segment = TF_Segment.getText(),
                    country = TF_Country.getText(),
                    city = TF_City.getText(),
                    state = TF_State.getText(),
                    region = TF_Region.getText(),
                    productid = TF_ProductID.getText(),
                    category = TF_Category.getText(),
                    subcategory = TF_Sub_Category.getText(),
                    productname = TF_ProductName.getText();

            int postalcode = Integer.parseInt(TF_Postal.getText()),
                    quantity = Integer.parseInt(TF_Quantity.getText());
            double sales = Double.parseDouble(TF_Sales.getText()),
                    discount = Double.parseDouble(TF_Discount.getText()),
                    profit = Double.parseDouble(TF_Profit.getText());
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");

            db.query.execute("INSERT INTO TenRecord"
                    + "(OrderId,OrderDate,ShipDate,ShipMode"
                    + ",CustomerId,CustomerName,Segment,Country,City,"
                    + "State,PostalCode,Region,ProductId,"
                    + "Category,SubCategory,ProductName,Sales,"
                    + "Quantity,Discount,Profit)"
                    + " VALUES ('" + orderid + "','" + orderdate + "','" + shipdate + "','"
                    + shipmode + "','" + customerid + "','" + customername + "','"
                    + segment + "','" + country + "','" + city + "','" + state + "','"
                    + postalcode + "','" + region + "','" + productid + "','"
                    + category + "','" + subcategory + "','" + productname + "','"
                    + sales + "','" + quantity + "','" + discount + "','" + profit + "')");
            db.commit();
            ab.getBarra().setValue(0);
            JOptionPane.showMessageDialog(this, "Datos agregados correctamente");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar datos");

        }

        db.desconectar();

    }//GEN-LAST:event_Bttn_AgregarRegistroMouseClicked

    private void Bttn_OrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bttn_OrdersMouseClicked
        jList_Registro.setModel(new DefaultListModel<>());
        DefaultListModel l = (DefaultListModel) jList_Registro.getModel();
        ab = new AdministrarBarra(jProgressBar1, 4, Color.green);
        ab.start();
        db.conectar();
        try {
            if (db != null && db.query != null) {
                db.query.execute("select OrderID,OrderDate,ShipDate,CustomerID from TenRecord");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    l.addElement("Order ID:" + rs.getString("OrderID"));
                    l.addElement("Order Date:" + rs.getString("OrderDate"));
                    l.addElement("Ship Date:" + rs.getString("ShipDate"));
                    l.addElement("Customer ID:" + rs.getString("CustomerID"));
                    l.addElement("\n");
                }
                ab.getBarra().setValue(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "Datos cargados exitosamente");
        jList_Registro.setModel(l);
        db.desconectar();
    }//GEN-LAST:event_Bttn_OrdersMouseClicked

    private void Bttn_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bttn_DetailsMouseClicked
        jList_Registro.setModel(new DefaultListModel<>());
        DefaultListModel l = (DefaultListModel) jList_Registro.getModel();
        ab = new AdministrarBarra(jProgressBar1, 5, Color.orange);
        ab.start();
        db.conectar();
        try {
            if (db != null && db.query != null) {
                db.query.execute("select OrderID,ProductID,Sales,Quantity,Discount,Profit from TenRecord");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    l.addElement("Order ID:" + rs.getString("OrderID"));
                    l.addElement("Product ID:" + rs.getString("ProductID"));
                    l.addElement("Sales:" + rs.getString("Sales"));
                    l.addElement("Quantity:" + rs.getString("Quantity"));
                    l.addElement("Discount:" + rs.getString("Discount"));
                    l.addElement("Profit:" + rs.getString("Profit"));
                    l.addElement("\n");
                }
                ab.getBarra().setValue(0);
                JOptionPane.showMessageDialog(this, "Datos cargados exitosamente");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jList_Registro.setModel(l);
        db.desconectar();
    }//GEN-LAST:event_Bttn_DetailsMouseClicked

    private void Bttn_CustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bttn_CustomersMouseClicked
        jList_Registro.setModel(new DefaultListModel<>());
        DefaultListModel l = (DefaultListModel) jList_Registro.getModel();
        ab = new AdministrarBarra(jProgressBar1, 6, Color.red);
        ab.start();
        db.conectar();
        try {
            if (db != null && db.query != null) {
                db.query.execute("select CustomerID,CustomerName,Segment,Country,City,State,PostalCode,Region from TenRecord");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    l.addElement("Customer ID:" + rs.getString("CustomerID"));
                    l.addElement("Customer Name:" + rs.getString("CustomerName"));
                    l.addElement("Segment:" + rs.getString("Segment"));
                    l.addElement("Country:" + rs.getString("Country"));
                    l.addElement("City:" + rs.getString("City"));
                    l.addElement("State:" + rs.getString("State"));
                    l.addElement("Postal Code:" + rs.getString("PostalCode"));
                    l.addElement("Region:" + rs.getString("Region"));
                    l.addElement("\n");
                }
                ab.getBarra().setValue(0);
                JOptionPane.showMessageDialog(this, "Datos cargados exitosamente");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jList_Registro.setModel(l);
        db.desconectar();
    }//GEN-LAST:event_Bttn_CustomersMouseClicked

    private void Bttn_ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bttn_ProductsMouseClicked
        jList_Registro.setModel(new DefaultListModel<>());
        DefaultListModel l = (DefaultListModel) jList_Registro.getModel();
        ab = new AdministrarBarra(jProgressBar1, 3, Color.blue);
        ab.start();
        db.conectar();
        try {
            if (db != null && db.query != null) {
                db.query.execute("select ProductID,Category,SubCategory,ProductName from TenRecord");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    l.addElement("Product ID:" + rs.getString("ProductID"));
                    l.addElement("Category:" + rs.getString("Category"));
                    l.addElement("Sub Category:" + rs.getString("SubCategory"));
                    l.addElement("Product name:" + rs.getString("ProductName"));

                    l.addElement("\n");
                }
                ab.getBarra().setValue(0);
                JOptionPane.showMessageDialog(this, "Datos cargados exitosamente");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jList_Registro.setModel(l);
        db.desconectar();
    }//GEN-LAST:event_Bttn_ProductsMouseClicked

    private void Bttn_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bttn_ClearMouseClicked
        jList_Registro.setModel(new DefaultListModel<>());
        DefaultListModel l = (DefaultListModel) jList_Registro.getModel();
        l.removeAllElements();
        jList_Registro.setModel(l);
    }//GEN-LAST:event_Bttn_ClearMouseClicked

    private void Bttn_UpdateTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bttn_UpdateTablaMouseClicked
        tabla.removeAll();
        Object d[] = new Object[8];
        DefaultTableModel tb = (DefaultTableModel) tabla.getModel();
        tb.setRowCount(0);
        db.conectar();
        try {
            if (db != null & db.query != null) {
                db.query.execute("select RowID,OrderID,OrderDate,CustomerID,Country,City,ProductID,Sales from TenRecord");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    d[0] = rs.getString("RowID");
                    d[1] = rs.getString("OrderID");
                    d[2] = rs.getString("OrderDate");
                    d[3] = rs.getString("CustomerID");
                    d[4] = rs.getString("Country");
                    d[5] = rs.getString("City");
                    d[6] = rs.getString("ProductID");
                    d[7] = rs.getString("Sales");
                    for (int i = 0; i < d.length; i++) {
                        tb.addRow(d);
                    }
                }
                JOptionPane.showMessageDialog(this, "Datos actualizados exitosamente");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tabla.setModel(tb);
        db.desconectar();
    }//GEN-LAST:event_Bttn_UpdateTablaMouseClicked

    private void Bttn_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bttn_EliminarMouseClicked
        int selectrow = tabla.getSelectedRow();
        ab = new AdministrarBarra(jProgressBar1, 5, Color.magenta);
        ab.start();
        db.conectar();
        if (selectrow >= 0) {
            try {
                if (db != null && db.query != null) {
                    db.query.execute("select OrderID,OrderDate,CustomerID,Country,City,ProductID,Sales from TenRecord");
                    ResultSet rs = db.query.getResultSet();
                    while (rs.next()) {
                        db.query.execute("delete from TenRecord where RowID=" + selectrow);
                        db.commit();
                    }
                    JOptionPane.showMessageDialog(this, "Dato eliminado, actualize la tabla");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            ab.getBarra().setValue(0);
        }
        db.desconectar();
    }//GEN-LAST:event_Bttn_EliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    AdministrarBarra ab;
    Dba db = new Dba("./TenRecord.accdb");
    int pos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttn_AgregarRegistro;
    private javax.swing.JButton Bttn_Clear;
    private javax.swing.JButton Bttn_Customers;
    private javax.swing.JButton Bttn_Details;
    private javax.swing.JButton Bttn_Eliminar;
    private javax.swing.JButton Bttn_Orders;
    private javax.swing.JButton Bttn_Products;
    private javax.swing.JButton Bttn_UpdateTabla;
    private javax.swing.JTextField TF_Category;
    private javax.swing.JTextField TF_City;
    private javax.swing.JTextField TF_Country;
    private javax.swing.JTextField TF_CustomerID;
    private javax.swing.JTextField TF_CustomerName;
    private javax.swing.JTextField TF_Discount;
    private javax.swing.JTextField TF_OrderDate;
    private javax.swing.JTextField TF_OrderID;
    private javax.swing.JTextField TF_Postal;
    private javax.swing.JTextField TF_ProductID;
    private javax.swing.JTextField TF_ProductName;
    private javax.swing.JTextField TF_Profit;
    private javax.swing.JTextField TF_Quantity;
    private javax.swing.JTextField TF_Region;
    private javax.swing.JTextField TF_Sales;
    private javax.swing.JTextField TF_Segment;
    private javax.swing.JTextField TF_ShipDate;
    private javax.swing.JTextField TF_ShipMode;
    private javax.swing.JTextField TF_State;
    private javax.swing.JTextField TF_Sub_Category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_Registro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
